import { Injectable } from '@angular/core'; // src/app/interceptors/auth.interceptor.ts // Default import added by Angular CLI is used to define an injectable service for intercepting HTTP requests like AuthInterceptor is used for adding auth tokens to requests
import {
  HttpRequest,
  HttpHandler,
  HttpEvent,
  HttpInterceptor
} from '@angular/common/http';
import { Observable } from 'rxjs';

@Injectable()
export class AuthInterceptor implements HttpInterceptor {

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {

    // Get token stored in the browser
    const token = localStorage.getItem("token");

    // If token exists, clone request and attach header
    if (token) {
      const authReq = req.clone({
        setHeaders: {
          Authorization: `Bearer ${token}`
        }
      });
      return next.handle(authReq);
    }

    // If no token, send request normally
    return next.handle(req);
  }


}// End of AuthInterceptor class this class is used mainly for adding authentication tokens generated by login route to outgoing HTTP requests for subsequent requests to protected API endpoints.
